#!/bin/bash
set -eu

if [ ! -d "${HOME}/.zprezto" ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${HOME}/.zprezto"
else
  git -C "${HOME}/.zprezto" pull
fi

mkdir -p "$HOME/code/src"
mkdir -p "$HOME/code/pkg"
mkdir -p "$HOME/code/bin"
