#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/nathanaelkane/vim-indent-guides.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-matchit.git",
  "git://github.com/tomtom/tcomment_vim.git",
  "git://github.com/vim-scripts/Gist.vim.git",
  "git://github.com/rson/vim-conque.git",
  "git://github.com/vim-scripts/railscasts.git",
  "git://github.com/vim-scripts/xorium.vim.git",
  "git://github.com/vim-scripts/xoria256.vim.git",
  "git://github.com/kien/ctrlp.vim"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
  ["TagList",       "7701",  "zip"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  if script_type == 'zip'
    local_file = File.join(name, "#{name}.#{script_type}")
  else
    local_file = File.join(name, script_type, "#{name}.vim")
  end
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    `unzip #{local_file} -d #{name}`
    FileUtils.rm_rf(local_file)
  end
end

