set runtimepath+=~/.vim/vundle.git/
call vundle#rc()

" Plugins setup
Bundle "fugitive.vim"
Bundle "Markdown"
Bundle "The-NERD-tree"
Bundle "Align"
Bundle "tComment"
Bundle "http://github.com/rstacruz/sparkup.git", {'rtp': 'vim/'}
Bundle "http://github.com/mattn/gist-vim.git"
Bundle "desert.vim"
Bundle "Wombat"
Bundle "sandvine"
Bundle "taglist.vim"
Bundle "python.vim"
Bundle "Conque-Shell"
Bundle "Solarized"

let mapleader = ","
let g:mapleader = ","

"enable 256 colors
set t_Co=256
set background=dark
colorscheme solarized



filetype plugin on

"Python magic
autocmd FileType python set omnifunc=pythoncomplete#Complete

"static tags
set tags+=$HOME/.vim/tags/python.ctags


syntax on
filetype plugin indent on
set tabstop=4
set smarttab
set shiftwidth=4
set autoindent
set smartindent
set expandtab


command MkGuard         call MakeIncGuard()
function MakeIncGuard()
	let basename = substitute(bufname(""), '.*/', '', '')
	let guard = '__' . substitute(toupper(basename), '\.', '_', "g") . '__'
	call append(0, "#ifndef " . guard)
	call append(1, "#define " . guard)
	call append(line("$"), "#endif")
endfunction


command MkScriptAuthor        call MakeScriptAuthor()
function MakeScriptAuthor()
	call append(1, "#coding: utf-8")
	call append(2, "#author: lxfontes")
endfunction


"Go save swap files somewhere else
if has("win32") || has("win64")
  set directory=$TMP
else
  set directory=/tmp
end

"no compatible
set nocompatible

"stop being annoying
set visualbell

set encoding=utf8

set ffs=unix,dos,mac "Default file type

"command completion
set wildmode=list:longest
set completeopt=longest,menuone


"my lil statusline (always on)
set laststatus=2
set statusline=%<%F%h%m%r%h%w%y\ %{&ff}\ %=\ lin:%l\,%L\ col:%c%V\ pos:%o\ ascii:%b\ %P


set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set ignorecase "Ignore case when searching
set smartcase

set hlsearch "Highlight search things

set incsearch "Make search act like search in modern browsers

" .h files
:autocmd BufNewFile *.h MkGuard

" JSON
au! BufRead,BufNewFile *.json setfiletype javascript

"sandvine policy
autocmd BufNewFile,BufRead policy*.conf set filetype=sandvine
autocmd BufNewFile,BufRead policy.conf set filetype=sandvine

"waf scripts
autocmd BufNewFile,BufRead wscript set filetype=python


"test
autocmd BufRead *.test                  setlocal filetype=cpp

"remember file position
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

" Highlight end of line whitespace.
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/





map <F1> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
nnoremap <silent> <F2> :NERDTreeToggle<CR>
nnoremap <silent> <F4> :tabprevious<CR>
nnoremap <silent> <F5> :tabnext<CR>
nnoremap <silent> <F8> :TlistToggle<CR>

" Remove the Windows ^M - when the encodings gets messed up
noremap <leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm
nnoremap <leader>p :tabprevious<CR>
nnoremap <leader>n :tabnext<CR>

nnoremap // :TComment<CR>
vnoremap // :TComment<CR>




function! s:Terminal()
    execute 'ConqueTermSplit bash --login'
endfunction
command! Terminal call s:Terminal()



" GUI options
if has("gui_running")
  " No menus and no toolbar
  set guioptions-=m
  set guioptions-=T
endif


" Appearance
set ruler
set title
set wrap
if exists("+colorcolumn")
  set colorcolumn=81
endif
set scrolloff=3


" MacVim
if has("gui_macvim")
    set transp=1
    set anti enc=utf-8 gfn=Menlo:h14,Monaco:h14
    set fuoptions=maxvert,maxhorz
endif

" Windows
if has("win32") || has("win64")
    " Use CUA keystrokes for clipboard: CTRL-X, CTRL-C, CTRL-V and CTRL-z
    source $VIMRUNTIME/mswin.vim
    set guifont=Consolas:h13:cANSI,Anonymous\ Pro:h13:cANSI
endif

"Specify the behavior when switching between buffers
 try
   set switchbuf=usetab
   set stal=2
 catch
 endtry


" Highlight current line
set cursorline
